# Generated by Django 5.2.4 on 2025-07-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'Активен'), ('CLOSED', 'Закрыт')], default='DRAFT', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
    ]
