# Generated by Django 5.2.4 on 2025-07-14 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('type', models.CharField(choices=[('SINGLE', 'Одиночный выбор'), ('MULTIPLE', 'Множественный выбор'), ('TEXT', 'Текстовый ответ')], max_length=10, verbose_name='Тип вопроса')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный вопрос')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
