# Generated by Django 5.2.4 on 2025-07-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_custom_answer',
            field=models.BooleanField(default=False, verbose_name='Добавить свой вариант'),
        ),
    ]
