# Generated by Django 5.2.4 on 2025-07-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='option',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
    ]
