# Generated by Django 5.2.4 on 2025-07-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_answer_option_alter_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='custom_answer',
        ),
    ]
